### ISSUE TITLE
No artist picture is displayed

### ISSUE THREAD

**Issue by yyartsworld** [timusus/Shuttle#438] opened 2019-02-27 10:41 UTC
**Shuttle version:**
 
 v2.0.8
 
**Device, OS:**

Galaxy Note 8, Android 8.0.0 

**Description of bug:**

No artist picture is displayed.
Nothing is displayed on artist information window.

**Steps to reproduce:**
 
 1. Go artist tab.
 2. No picture is displayed.
 3. Select artist information
 4. Nothing is displayed
 
**Expected outcome:**
 
Expected outcome here
 
**Observations/Actual Result:**
 
 Observations here
![screenshot_20190227-192951_shuttle](https://user-images.githubusercontent.com/24272805/53484646-a43ee900-3ac7-11e9-9fc5-2109787af8ea.jpg)

**Comment by timusus** [comment] 2019-02-27 10:42
Duplicate of #425

**Closed by timusus** 2019-02-27 10:42 UTC
