### ISSUE TITLE
Opus files are not recognised / don't play.

### ISSUE THREAD

**Issue by krompus** [timusus/Shuttle#182] opened 2017-09-07 17:15 UTC
I added some opus files to my music directory, and rescanned the folders, but they don't show up in the folder browser. These files play just fine in other music players.

They don't play if I manually select them from my file manager and try to open with Shuttle either.

Shuttle Free with IAP, running on a Google Pixel, stock Oreo. Rebooted and issue persists.

I'm trying to save some space on my wee 32GB phone; I'd really like opus support!

I'll use ogg for now I guess. :P

Edit: SOME ogg files don't play either. Weird.

**Comment by timusus** [comment] 2017-09-07 21:28
Thanks for the report.

When choosing other players are you testing on? Does I work on your stock player / play music?

Also, see #2

**Comment by timusus** [comment] 2017-10-10 03:30
Closing due to lack of information & likely duplicate of #2.

**Closed by timusus** 2017-10-10 03:30 UTC
