### ISSUE TITLE
Songs on SD card removed from all playlists after power cycle

### ISSUE THREAD

**Issue by dbrakman** [timusus/Shuttle#444] opened 2019-03-17 03:09 UTC
**Shuttle version:**

 2.0.10 (Free)

**Device, OS:**
Samsung Galaxy S9
Android 9
SanDisk 32GB MicroSDHC card

**Description of bug:**
 
Whenever I restart my phone, songs on my SD card disappear from any playlists they were in.
 
**Steps to reproduce:**
 
 1. Using a file browser, download or save several songs into `/Samsung/Music/`, and several other songs into `/SD card/Music`
 2. In Shuttle, create 3 playlists: 'device', 'sd-card', and 'mixed', containing songs saved to the device and songs saved to the SD card
 3. Restart the phone.
 
**Expected outcome:**
 
Playlist contents are unchanged after restarting the phone.
 
**Observations/Actual Result:**
 
After restarting the phone, the 'device' playlist is unchanged, the 'sd-card' playlist is empty, and the 'mixed' playlist contains only songs saved to the device.

A tangential observation is that when Shuttle is first opened after a restart, it takes about 45 seconds for songs from the SD card to display in the Library.

**Screenshots:**

Before restart:
![Screenshot_20190316-193958_Shuttle](https://user-images.githubusercontent.com/15183484/54484627-cb1b5000-4827-11e9-8192-6de981a516d0.jpg)

After restart:
![Screenshot_20190316-195826_Shuttle](https://user-images.githubusercontent.com/15183484/54484628-ceaed700-4827-11e9-9c69-b00ceafea8e5.jpg)

**Comment by different55** [comment] 2019-04-19 13:03
Possibly worth noting this isn't exclusive to Shuttle. I had the same problem over on Vinyl.

**Comment by timusus** [comment] 2019-05-14 08:59
This is an issue with Android itself. I need to implement a workaround, but I'm not currently working on it.

Duplicate of #330, #101

**Closed by timusus** 2019-05-14 08:59 UTC
Labels: framework-bug
