### ISSUE TITLE
Shuttle Crashes when phone is rotated and goes into landscape mode

### ISSUE THREAD

**Issue by Citreon** [timusus/Shuttle#429] opened 2019-02-14 14:40 UTC
**Shuttle version:**
 
 v2.0.8-beta 2
 
**Device, OS:**
 
Huawei v10, 8.1.0

**Description of bug:**
 
When phone is rotated to landscape mode, shuttle will crash
 
**Steps to reproduce:**
 
 1. have music playing in portrait mode
 2. rotate phone
 3. music stops playing and shuttle closes
 
**Expected outcome:**
 
music to still be playing

**Observations/Actual Result:**
 
 Observations here

**Comment by GeoZac** [comment] 2019-02-14 14:42
Resolved in v2.0.8-beta4 
Duplicate of #423

**Closed** 2019-02-26 11:38 UTC
