### ISSUE TITLE
Music randomly stops (app crashes?)

### ISSUE THREAD

**Issue by kaio77** [timusus/Shuttle#358] opened 2018-06-25 23:58 UTC
**Shuttle version:**
 
 v2.0.5-beta6
 
**Device, OS:**
 
Pixel 2, Android P Beta 3

**Description of bug:**
 
Music will randomly stop playing.  I check my phone and the Shuttle app is not there anymore.  I reopen the app and am able to restart the music where it stopped playing.  It's as if someone closed the app.
 
**Steps to reproduce:**
 
1. Start playing music and just wait.  Happens randomly.
 
**Expected outcome:**
 
App will close.
 
**Observations/Actual Result:**
 
It's random, doesn't happen all the time.  Unpredictable.

**Comment by timusus** [comment] 2018-06-26 00:06
Thanks for the report @kaio77.

Does this ever happen when the screen is on, or while you are actively browsing the app? 

Do you usually get through a few songs, or does this happen closer to the start of the session?

Any information at all about what you've noticed would be useful. If you're able, it would also be great if you could provide some system logs around the time the issue occurs - but this requires some more technical knowledge of Android.

**Comment by timusus** [comment] 2018-06-26 00:10
Related / possible duplicate of #343

**Comment by Bluerobot1234** [comment] 2018-08-06 11:28
Managed to catch it while the app was open. The music just stops in place, now playing says it's paused but the mini player says it's playing. Pressing play just plays the animation between play and pause every time and doesn't actually play the music. Closing the app from recents and then reopening fixes it.

OnePlus 3T Android 8.0
Shuttle+ Beta 7

**Comment by timusus** [comment] 2018-08-06 11:33
@Bluerobot1234 have you got access to system logs? Can you reproduce this reliably, or was it just a once off?

**Comment by Bluerobot1234** [comment] 2018-08-06 12:09
Not sure how to access system logs on my phone and this bug happens almost on random. Doesn't matter what's running

**Comment by kaio77** [comment] 2018-08-09 01:27
In my experience, I do get through a couple of songs.  My phone's always in my pocket when it has happened (screen off).

However, it has not happened recently, so no issues so far.

**Comment by TanaTanoi** [comment] 2018-08-22 04:53
I've had this happen recently too. I'll just be listening to it, screen off with headphones, then it stops playing and the notification disappears. I'll press the play button on my headphones and it'll start up again in a few seconds (the same as when you do it from a closed app).

It happens fairly inconsistently in terms of frequency (can go a whole hour or only 2 songs before it happens).

It only started happening recently, roughly once I upgraded to Shuttle+ (12 days ago).

Shuttle version: 2.0.5 (Upgraded)
Android 7.1.1
Moto G5s XT1805

**Comment by timusus** [comment] 2018-08-24 03:51
Can anyone confirm whether the issue occurs when bluetooth is turned off?

**Comment by TanaTanoi** [comment] 2018-08-24 03:58
I'll try running it a while without Bluetooth and let you know on Monday if it ever happens

**Comment by TorstenL** [comment] 2018-08-24 04:00
It happens independently of whether the Bluetoothstate is.

**Comment by TanaTanoi** [comment] 2018-08-24 04:08
Can confirm, just happened

**Comment by timusus** [comment] 2018-08-24 04:11
OK, thanks for the info.

Is there anything else happening on the device when music pauses? Any kind of information at all which might help track down the cause of the pause..

If anyone has access to system logs, if they're able to record them and post them after music randomly stops playing, that would be super helpfui.

**Comment by timusus** [comment] 2018-09-03 11:56
Fixed with v2.0.6.

**Comment by farmerbb** [comment] 2018-11-29 23:32
FYI, I'm seeing this issue occur again with 2.0.7-beta8.  Music will randomly stop while playing via Bluetooth, and the track will start over once playback is manually resumed.

**Comment by farmerbb** [comment] 2018-12-04 19:07
Still occurring with 2.0.7-beta10

**Closed** 2018-12-06 08:18 UTC
Labels: bug, high-priority

**Comment by cpolishak** [comment] 2019-11-04 15:14
Hello, I'm having the same issue now with bluetooth on and off. Will look into how to catch system logs to capture them to try and help. I'm on the latest Android build and shuttle 2.0.12.

**Comment by RobbFlynn666** [comment] 2019-11-18 07:35
hi all, happening to me as well, maybe once a day.
using EMUI 9.1.0, bluetooth on(don't listen to music otherwise but if needed i can test it).
shuttke version 2.0.12
usually the phone is in my pocket and don't interact with it. I also have the habit of not leaving open apps(occasionally there might be a google maps session...).
