### ISSUE TITLE
Shuffle/repeat button color issue

### ISSUE THREAD

**Issue by neekless** [timusus/Shuttle#374] opened 2018-09-06 01:36 UTC
**Shuttle version:**
Shuttle+ v2.0.6
 
**Device, OS:**
Pixel 2 XL Android 8.1

**Description of bug:**
Now playing screen shuffle and repeat buttons show accent color only on first run, after that is white through all modes, making it impossible to tell if it's on or not without toggling it.
 
**Steps to reproduce:**
1. Install shuttle(+)
2. Setup theme and accent color
3. Play a song, go to now playing screen, toggle shuffle or repeat mode. Observe those buttons turning to accent color when they are on.
4. Leave the app and open again. Shuffle and repeat buttons are now white. Toggle them and they'll still be white. Only the toast messages will let you know if they're on or off.
 
**Expected outcome:**
Shuffle and repeat buttons should consistently be the accent color if they are toggled on.
 
**Observations/Actual Result:**
Shuffle and repeat buttons are white. Toggle them and they'll still be white. Only the toast messages will let you know if they're on or off.

**Comment by GeoZac** [comment] 2018-09-06 03:55
Duplicate of #355

**Comment by jnpatel2811** [comment] 2018-10-06 22:02
#382

**Closed** 2019-06-03 15:32 UTC
Labels: bug, duplicate
