### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by flxholle** [timusus/Shuttle#500] opened 2020-06-06 09:54 UTC
I created a "tracker-free" version of the dev and master branch, see #499 
Now I'd like to add them to F-Droid. Currently the F-Droid source code is linked on my repository but if the pull request will be merged in a new branch, I switch the link to source code.
Here is the matching merge request on GitLab for adding this app to the official F-Droid catalogue: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6903

**Comment by timusus** [comment] 2020-06-14 11:54
Thanks @asdoi. Appreciate your work. Just closing this issue as a duplicate of #28

**Closed as completed by timusus** 2020-06-14 11:54 UTC
