### ISSUE TITLE
Play Next does not work after Go to...

### ISSUE THREAD

**Issue by jsbruglie** [timusus/Shuttle#313] opened 2018-03-23 08:37 UTC
**Shuttle version:**
 
 v2.0.3 (Free)
 
**Device, OS:**
 
Moto G 3, Android 6.0.1

**Description of bug:**
 
Play next does not work, after Goto Album for instance.
 
**Steps to reproduce:**
 
 1. Play any track
 2. Top-right corner
 3. Go to...
 4. Album
 5. Try Play Next in any of the tracks
 
**Expected outcome:**
 
Popup stating track has been added to playlist and added right after currently playing track.
 
**Observations/Actual Result:**
 
 Nothing happens.

**Comment by GeoZac** [comment] 2018-03-23 09:03
Duplicate of #283 and fixed in 2.0.4-beta1

**Closed** 2018-03-25 05:42 UTC
