### ISSUE TITLE
Creating a new playlist from a folder gets stuck at "Gathering songs..."

### ISSUE THREAD

**Issue by newtant** [timusus/Shuttle#229] opened 2017-11-25 08:28 UTC
**Shuttle version:**
 
 v1.6.7
 
**Device, OS:**
 
OnePlus 3T, OOS, LineageOS, Paranoid Android
ext4

**Description of bug:**
 
Creating a new playlist from a folder gets stuck at "Gathering songs...", reopening the app (as in, switching out of it, swiping it away in Recents, and opening it again) shows that the new playlist exists, but is empty. Afterwards the playlist works as expected.
 
**Steps to reproduce:**
 
 1. From the sidebar open Library -> and switch to the Folder tab or open the sidebar Folder view itself 
 2. Open the breadcrumb menu from a folder with music files in it
 3. Add to playlist
4. New
5. Enter a name
6. Save
7. "Gathering songs..."
 
**Expected outcome:**
 
A new playlist with the previously entered name & containing the songs from the chosen folder has been created.
 
**Observations/Actual Result:**
 
 The app seems to be stuck at "Gathering songs...", pressing back several times goes back to the homescreen. Opening the app again immediately returns to the "Gathering songs..." state. Closing it, swiping it away from Recents and opening Shuttle again returns the app to working order.
The created playlist exists, has the correct name, but is empty. Functionality doesn't seem to be affected at all.

**Comment by timusus** [comment] 2017-12-10 05:31
I'm not able to reproduce this issue on my device, which is making things difficult. Will keep testing.

**Comment by timusus** [comment] 2018-03-12 06:19
Duplicate of #113

**Closed by timusus** 2018-03-12 06:19 UTC
Labels: bug
