### ISSUE TITLE
Add ability to change speed of song

### ISSUE THREAD

**Issue by catzs** [timusus/Shuttle#117] opened 2017-08-05 03:50 UTC
I love listening to some music a bit faster than the original speed. VLC is great at this; offering the ability to speed up the song WITHOUT changing the pitch. It's also open source ;)

**Comment by timusus** [comment] 2017-12-17 13:06
Depends on #245

**Comment by timusus** [comment] 2018-08-16 10:58
Duplicate of #41

**Closed by timusus** 2018-08-16 10:58 UTC
Labels: enhancement
