### ISSUE TITLE
Playlists deleted

### ISSUE THREAD

**Issue by damoulou** [timusus/Shuttle#330] opened 2018-04-21 16:59 UTC
**Shuttle version:**
 
 v2.0.4
 
**Device, OS:**
 
One plus 5t A5010
Android 8.1.0

**Description of bug:**
 
My playlists are deleted when (I think) I connect and then disconnect my Phone to my computer in file transfer mode
 
**Steps to reproduce:**
 
 1. Connect Phone to pc
 2. Switch to file transfer mode
 3. Disconnect Phone
 
**Observations/Actual Result:**

All playlists are deleted

**Comment by GeoZac** [comment] 2018-04-22 04:30
@damoulou Please do check open issues before posting one.
Duplicate of #101

**Closed** 2018-04-28 06:47 UTC
