### ISSUE TITLE
Status bar icons blending into dark artwork

### ISSUE THREAD

**Issue by andrewvaccaro** [timusus/Shuttle#206] opened 2017-10-21 19:40 UTC
**Shuttle version:**
 
 v2.0.0-beta12
 
**Device, OS:**
 
Pixel 2 XL 8.0

**Description of bug:**
 
Album and artist screens hide status bar icons if they're dark on the light theme

https://imgur.com/a/tfkLK
 
**Steps to reproduce:**
 
 1. Use light theme
 2. Visit any artist or album page with a dark background
 
**Expected outcome:**

Status bar icons should be visible regardless of artwork color, possibly using semi opaque gradient or white icons.

**Comment by timusus** [comment] 2017-10-22 22:01
Thanks for the report. 

Duplicate of #196

**Closed by timusus** 2017-10-22 22:01 UTC
